### ISSUE TITLE
[BUG] Code in setup not executed

### ISSUE THREAD

**Issue by lukaskurz** [Dynatrace/zakzak#13]
I have some code inside a `setup()` function that should be executed before the benchmark, but somehow isn't

## Description

The code in question should initialize a variable which is used in the benchmark.
However, when running the benchmark, the variable is undefined and the benchmark crashes.
Either the setup code is not executed (most likely) or the benchmark has a different context and simply accesses a non existent variable.

## Expected Behavior

Variable should be initialized during setup phase and benchmark should not crash

## Actual Behavior

Variable is undefined during benchmark, results in crash.

## Possible Fix

Maybe crashes during the Asynchronity check. Check should be done after setup phase.

## Steps to Reproduce

1. Run zakzak on this code

```ts
import { Loader } from "../someLoader";
import { suite, setup, benchmark } from "@dynatrace/zakzak";

suite("SomeThing", () => {
    let some: SomeThing;
    setup(() => {
        const loader = new Loader();
	some = loader.load();
    });
    suite("doStuff()", () => {
        benchmark("constant param", () => {
            some.doStuff("test123");
        });
    });
});
```

## Your Environment

* Version used: v0.2.1
* Environment name and version (e.g. node 10.15.2 and npm 6.4.1): node v10.16.1, npm 6.9.0
* Operating System and version: Ubuntu 18.04

**Comment by lukaskurz** [comment]
Error log i forgot to include
```
lukas@lukas-pc:~/somepath$ npx zakzak
 ________  ________  ___  __    ________  ________  ___  __       
|\_____  \|\   __  \|\  \|\  \ |\_____  \|\   __  \|\  \|\  \     
 \|___/  /\ \  \|\  \ \  \/  /|_\|___/  /\ \  \|\  \ \  \/  /|_   
     /  / /\ \   __  \ \   ___  \   /  / /\ \   __  \ \   ___  \  
    /  /_/__\ \  \ \  \ \  \\ \  \ /  /_/__\ \  \ \  \ \  \\ \  \ 
   |\________\ \__\ \__\ \__\\ \__\\________\ \__\ \__\ \__\\ \__\
    \|_______|\|__|\|__|\|__| \|__|\|_______|\|__|\|__|\|__| \|__|
                                                                  
                                                                  
                                                                  
╔═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╤═════════════════╗
║ Name            │ Measurements    │ Cycles          │ Mean            │ Median          │ Mode            │ StdDev          │ StdErr          │ MoE             │ Min             │ Max             ║
╚═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╧═════════════════╝(node:9258) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'doStuff' of undefined
    at Benchmark.zakzak_1.benchmark [as fn] (/home/lukas/somepath/benchmark/some.benchmark.js:13:16)
    at Benchmark.isAsync (/home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/benchmark/benchmark.js:127:24)
    at Benchmark.<anonymous> (/home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/benchmark/benchmark.js:99:31)
    at Generator.next (<anonymous>)
    at /home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/benchmark/benchmark.js:24:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/benchmark/benchmark.js:20:12)
    at Benchmark.start (/home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/benchmark/benchmark.js:98:16)
    at ChildProcessHandler.<anonymous> (/home/lukas/somepath/node_modules/@dynatrace/zakzak/dist/src/process/child-process.js:90:48)
    at Generator.next (<anonymous>)
(node:9258) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:9258) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```
